-- NEXUS Platform — 0008: reference data (plans & AI employee templates)
-- Prices are in halalas (SAR × 100). Annual billing only. `null` limit = unlimited.

insert into public.subscription_plans (code, name_ar, name_en, price_halalas, is_popular, is_custom, entitlements, sort_order) values
('starter', 'المبتدئة', 'Starter', 39900, false, false, '{
  "human_members": 1, "ai_employees": 3, "ai_executions_per_year": 300, "active_projects": 5,
  "storage_bytes": 5368709120, "max_file_size_bytes": 26214400, "concurrent_ai_sessions": 1, "computer_minutes_per_year": 600,
  "features": ["basic_memory", "basic_analytics"]
}'::jsonb, 1),
('pro', 'الاحترافية', 'Pro', 59900, true, false, '{
  "human_members": 5, "ai_employees": 10, "ai_executions_per_year": 1500, "active_projects": null,
  "storage_bytes": 26843545600, "max_file_size_bytes": 52428800, "concurrent_ai_sessions": 3, "computer_minutes_per_year": 3000,
  "features": ["basic_memory", "full_memory", "knowledge", "decisions", "meetings", "approvals", "agent_orchestration", "basic_analytics", "advanced_analytics"]
}'::jsonb, 2),
('business', 'الأعمال', 'Business', 99900, false, false, '{
  "human_members": 15, "ai_employees": 30, "ai_executions_per_year": 5000, "active_projects": null,
  "storage_bytes": 107374182400, "max_file_size_bytes": 104857600, "concurrent_ai_sessions": 8, "computer_minutes_per_year": 12000,
  "features": ["basic_memory", "full_memory", "knowledge", "decisions", "meetings", "approvals", "advanced_approvals", "agent_orchestration", "advanced_orchestration", "basic_analytics", "advanced_analytics", "advanced_permissions", "audit_logs", "priority_support", "archive_uploads"]
}'::jsonb, 3),
('enterprise', 'المؤسسات', 'Enterprise', null, false, true, '{
  "human_members": null, "ai_employees": null, "ai_executions_per_year": null, "active_projects": null,
  "storage_bytes": null, "max_file_size_bytes": 262144000, "concurrent_ai_sessions": 20, "computer_minutes_per_year": null,
  "features": ["basic_memory", "full_memory", "knowledge", "decisions", "meetings", "approvals", "advanced_approvals", "agent_orchestration", "advanced_orchestration", "basic_analytics", "advanced_analytics", "advanced_permissions", "audit_logs", "priority_support", "archive_uploads"]
}'::jsonb, 4)
on conflict (code) do update set
  name_ar = excluded.name_ar, name_en = excluded.name_en, price_halalas = excluded.price_halalas,
  is_popular = excluded.is_popular, is_custom = excluded.is_custom, entitlements = excluded.entitlements, sort_order = excluded.sort_order;

insert into public.ai_employee_templates (code, category, name_ar, name_en, job_title_ar, job_title_en, description_ar, description_en, responsibilities, skills, default_permissions, default_autonomy, sort_order) values
('chief_executive', 'executive', 'أطلس', 'Atlas', 'وكيل الرئيس التنفيذي', 'Chief Executive Agent', 'يوجّه الأولويات ويعد الملخصات التنفيذية ومذكرات القرار.', 'Sets priorities and prepares executive briefs and decision memos.', '["Executive briefs","Decision memos","Priority alignment"]', '["strategy","leadership","synthesis"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,memory.write,decisions.read,delegate,files.shared.view,files.own.modify}', 'draft', 1),
('strategy', 'executive', 'رؤى', 'Ruaa', 'وكيل الاستراتيجية', 'Strategy Agent', 'يحلل الأسواق ويبني الخطط الاستراتيجية.', 'Analyzes markets and builds strategic plans.', '["Strategic plans","Scenario analysis"]', '["strategy","analysis"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,decisions.read,files.shared.view,files.own.modify}', 'draft', 2),
('chief_of_staff', 'executive', 'سند', 'Sanad', 'رئيس الديوان', 'Chief of Staff', 'ينسق بين الإدارات ويتابع تنفيذ المهام.', 'Coordinates departments and tracks execution.', '["Follow-ups","Meeting summaries","Status reports"]', '["coordination","reporting"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,delegate,files.own.modify}', 'draft', 3),
('product_manager', 'product', 'نور', 'Noor', 'مدير المنتج', 'Product Manager', 'يكتب المتطلبات ويحدد أولويات خارطة الطريق.', 'Writes requirements and prioritizes the roadmap.', '["PRDs","Roadmaps","Prioritization"]', '["product","requirements"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,files.shared.view,files.own.modify}', 'draft', 10),
('ux_researcher', 'product', 'مها', 'Maha', 'باحثة تجربة المستخدم', 'UX Researcher', 'تعد أبحاث المستخدمين وتحلل الملاحظات.', 'Plans user research and analyzes feedback.', '["Research plans","Insight reports"]', '["research","ux"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.shared.view,files.own.modify}', 'draft', 11),
('product_analyst', 'product', 'فيصل', 'Faisal', 'محلل المنتج', 'Product Analyst', 'يحلل مقاييس المنتج ويقترح التحسينات.', 'Analyzes product metrics and proposes improvements.', '["Metric analysis","Experiment reports"]', '["analytics","data"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.shared.view,files.own.modify}', 'draft', 12),
('cto', 'engineering', 'تقني', 'Taqni', 'الرئيس التقني', 'CTO', 'يضع التوجه التقني ويراجع المعمارية.', 'Sets technical direction and reviews architecture.', '["Architecture reviews","Tech strategy"]', '["architecture","engineering"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,delegate,files.shared.view,files.own.modify}', 'draft', 20),
('software_architect', 'engineering', 'بنّاء', 'Bannaa', 'مهندس معماري للبرمجيات', 'Software Architect', 'يصمم الأنظمة ويكتب الوثائق التقنية.', 'Designs systems and writes technical specs.', '["System design","Technical specs"]', '["architecture","documentation"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 21),
('backend_engineer', 'engineering', 'خادم', 'Khadim', 'مهندس الواجهات الخلفية', 'Backend Engineer', 'يخطط ويوثق خدمات الواجهة الخلفية.', 'Plans and documents backend services.', '["API design","Technical reports"]', '["backend","apis"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 22),
('frontend_engineer', 'engineering', 'واجهة', 'Wajha', 'مهندس الواجهات الأمامية', 'Frontend Engineer', 'يخطط واجهات المستخدم ويوثق المكونات.', 'Plans user interfaces and documents components.', '["UI specs","Component docs"]', '["frontend","ui"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 23),
('qa_engineer', 'engineering', 'دقيق', 'Daqeeq', 'مهندس ضمان الجودة', 'QA Engineer', 'يكتب خطط الاختبار ويحلل الجودة.', 'Writes test plans and analyzes quality.', '["Test plans","Bug reports"]', '["testing","quality"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 24),
('cmo', 'marketing', 'صدى', 'Sada', 'الرئيس التسويقي', 'CMO', 'يقود الاستراتيجية التسويقية وتموضع العلامة.', 'Leads marketing strategy and brand positioning.', '["Marketing strategy","Campaign plans"]', '["marketing","brand"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,delegate,files.shared.view,files.own.modify}', 'draft', 30),
('market_researcher', 'marketing', 'باحث', 'Bahith', 'باحث السوق', 'Market Researcher', 'يعد دراسات السوق وتحليل المنافسين.', 'Prepares market studies and competitor analysis.', '["Market research","Competitor analysis"]', '["research","markets"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.shared.view,files.own.modify}', 'draft', 31),
('content_strategist', 'marketing', 'قلم', 'Qalam', 'استراتيجي المحتوى', 'Content Strategist', 'يخطط المحتوى ويكتب المسودات.', 'Plans content and writes drafts.', '["Content calendars","Copy drafts"]', '["writing","content"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 32),
('growth', 'marketing', 'نمو', 'Numuw', 'وكيل النمو', 'Growth Agent', 'يصمم تجارب النمو ويحلل النتائج.', 'Designs growth experiments and analyzes results.', '["Growth experiments","Funnel analysis"]', '["growth","analytics"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 33),
('sales_manager', 'sales', 'صفقة', 'Safqa', 'مدير المبيعات', 'Sales Manager', 'يبني خطط المبيعات ويتابع الفرص.', 'Builds sales plans and tracks opportunities.', '["Sales plans","Pipeline reviews"]', '["sales","negotiation"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,files.own.modify}', 'draft', 40),
('lead_research', 'sales', 'رادار', 'Radar', 'وكيل أبحاث العملاء المحتملين', 'Lead Research Agent', 'يبحث عن العملاء المحتملين ويؤهلهم.', 'Researches and qualifies leads.', '["Lead lists","Account research"]', '["research","prospecting"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.own.modify}', 'draft', 41),
('cfo', 'finance', 'ميزان', 'Mizan', 'الرئيس المالي', 'CFO', 'يعد التحليلات والتوقعات المالية.', 'Prepares financial analyses and forecasts.', '["Financial plans","Budget reviews"]', '["finance","planning"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.shared.view,files.own.modify}', 'suggest', 50),
('financial_analyst', 'finance', 'رقم', 'Raqam', 'محلل مالي', 'Financial Analyst', 'يحلل البيانات المالية ويعد التقارير.', 'Analyzes financial data and prepares reports.', '["Financial reports","Variance analysis"]', '["finance","analysis"]', '{documents.create,documents.read,tasks.read,tasks.update_own,memory.read,files.shared.view,files.own.modify}', 'suggest', 51),
('operations_manager', 'operations', 'مسار', 'Masar', 'مدير العمليات', 'Operations Manager', 'يحسن العمليات ويتابع الأداء التشغيلي.', 'Improves processes and tracks operational performance.', '["Process docs","Ops reports"]', '["operations","process"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,delegate,files.own.modify}', 'draft', 60),
('project_coordinator', 'operations', 'منسق', 'Munassiq', 'منسق المشاريع', 'Project Coordinator', 'ينسق الجداول الزمنية ويتابع المهام.', 'Coordinates timelines and follows up on tasks.', '["Project plans","Status updates"]', '["planning","coordination"]', '{documents.create,documents.read,tasks.read,tasks.update_own,tasks.create,memory.read,files.own.modify}', 'draft', 61)
on conflict (code) do nothing;
